# Generated by Django 3.0.8 on 2020-07-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pativirakka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.ManyToManyField(to='pativirakka.Education'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='experience',
        ),
        migrations.AddField(
            model_name='person',
            name='experience',
            field=models.ManyToManyField(to='pativirakka.Experience'),
        ),
    ]
