# Generated by Django 3.0.8 on 2020-07-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pativirakka', '0002_auto_20200727_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='pativirakka.Skills'),
        ),
    ]
