# Generated by Django 3.0.8 on 2020-07-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pativirakka', '0003_person_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('', 'Skill level'), ('b', 'Beginner'), ('e', 'Elementary'), ('pi', 'Pre-intermediate'), ('i', 'Intermediate'), ('ui', 'Upper-intermediate'), ('a', 'Advanced')], help_text='<b>Beginner Elementary Pre-intermediate</b> try to <u>not Include</u>', max_length=2),
        ),
    ]
