# Generated by Django 3.0.8 on 2020-07-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pativirakka', '0004_auto_20200727_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='social_links',
            field=models.ManyToManyField(to='pativirakka.Social_links'),
        ),
    ]
