# Generated by Django 3.0.8 on 2020-07-26 21:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pativirakka', '0005_auto_20200727_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_more',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AddField(
            model_name='person',
            name='add_more',
            field=models.ManyToManyField(to='pativirakka.Add_more'),
        ),
    ]
